# yaml-language-server: $schema=https://schema.blue-build.org/module-stage-list-v1.json
modules:
- type: dnf
  repos:
    copr:
      - ublue-os/staging
  install:
    packages:
      - just
      - netcat