# yaml-language-server: $schema=https://schema.blue-build.org/module-stage-list-v1.json
modules:
- type: dnf
  repos:
    files:
      - vscode.repo
      - google-chrome.repo
  install:
    packages:
      - google-chrome-stable
      - code
      - libvirt
      - virt-manager
      - toolbox
      - distrobox
      # - just
      - fastfetch
      - cockpit-machines
      - cockpit-networkmanager
      - cockpit-ostree
      - cockpit-bridge
      - cockpit-podman
      - cockpit-selinux
      - cockpit-storaged
      - cockpit-system
      
  optfix:
    - google