modules:
- type: dnf
  repos:
    files:
      - vscode.repo
      - google-chrome.repo
    copr:
      - ublue-os/staging
  install:
    packages:
      - google-chrome-stable
      - code
      - distrobox
      - just
      - libvirt
      - virt-manager
      - netcat
      - fastfetch
      - cockpit-machines
      - cockpit-networkmanager
      - cockpit-ostree
      - cockpit-bridge
      - cockpit-podman
      - cockpit-selinux
      - cockpit-storaged
      - cockpit-system
  optfix:
    - google
  remove:
    packages:
      # atd does not work on an atomic image
      # see https://github.com/fedora-silverblue/issue-tracker/issues/563
      - at